apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "transmission.name" . }}
    helm.sh/chart: {{ include "transmission.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "transmission.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "transmission.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: TZ
              value: "{{ .Values.timezone }}"
            - name: PUID
              value: "{{ .Values.puid }}"
            - name: PGID
              value: "{{ .Values.pgid }}"
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /downloads
              name: downloads
            {{- if .Values.persistence.downloads.subPath }}
              subPath: {{ .Values.persistence.downloads.subPath }}
            {{- end }}
            {{- range .Values.persistence.extraExistingClaimMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly }}
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: downloads
      {{- if .Values.persistence.downloads.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.downloads.existingClaim }}{{ .Values.persistence.downloads.existingClaim }}{{- else }}{{ template "transmission.fullname" . }}-downloads{{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- range .Values.persistence.extraExistingClaimMounts }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .existingClaim }}
      {{- end }}
{{- if and .Values.persistence.config.enabled .Values.persistence.config.existingClaim }}
      - name: config
      {{- if .Values.persistence.config.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.config.existingClaim }}
      {{- else }}
        emptyDir: {}
      {{- end }}
{{- else if not .Values.persistence.config.enabled }}
      - name: config
        emptyDir: {}
{{- else if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) }}
  volumeClaimTemplates:
  - metadata:
      name: config
      labels:
        app.kubernetes.io/name: {{ include "transmission.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      accessModes: 
        - {{ .Values.persistence.config.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.config.size | quote }}
      {{- if .Values.persistence.config.storageClass }}
      {{- if (eq "-" .Values.persistence.config.storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: "{{ .Values.persistence.config.storageClass }}"
      {{- end }}
      {{- end }}
{{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
